/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "registers.h"

#define SET_PIN_VALUE(x) ((1 << 2*x) & (~(1 << (2*x+1))))  // 10 ... 2x = 1, 2x+1 = 0 // OUTPUT PIN MODE

void delay(void) {
	for(uint32_t i = 0; i < 10000; i++) {}
}


int main(void)
{

	// Give CLOCK to enable GPIO_D port which is 3rd bit
	RCC_CLK_REG_ABH1 = RCC_CLK_REG_ABH1 | GPIO_D_PIN_EN ;

	// To tell what kind of behavior PIN should act :  output mode
	GPIO_D_MODER = GPIO_D_MODER | SET_PIN_VALUE(PIN);


	while(1) {
       // enable LED
		GPIOD_ODR_VALUE = GPIOD_ODR_VALUE | LED_USED;
		delay();

		//disable LED
		GPIOD_ODR_VALUE = GPIOD_ODR_VALUE & ~(LED_USED);
		delay();
	}
}
